### ISSUE TITLE
这个的话还是挺方便 但是有个建议 ，它可以自定义变量名吗 

### ISSUE THREAD

**Issue by corsgoo** [moon-cn/qinglong-jd-app#15]
rt。因为他有些脚本获取这个 但是并不一定就是这个名字 ，对于我们对代码不熟悉的也没办法去改它的脚本 。如果可以自定义上传的这个变量名就好了

**Comment by jiangood** [comment]
可以，正好最近有时间了

**Comment by corsgoo** [comment]
> 可以，正好最近有时间了

nice。其实我最近我发现有一个比较小众的需求(别的) ，不知道您这边有时间的话是否可以看一看能不能也做个类似的 青龙脚本或docker运行或者apk也可以。
京东有一个APP叫京东云无线宝 ，很多朋友都有用那种 监工的软件 ，需要抓包无限宝里面的tgt参数拿来登录获取信息。但是这个抓包很麻烦 ，所以我一直有个想法 ，如果有大哥可以研究一下京东的ck和京东云无线宝的tgt的关系。
(京东CK不知道是否可以直接登录京东无限宝 ，然后再通过某种技术手段直接抓取tgt，就不需要我们直接打开无限宝APP用抓包软件去抓了 )。因为京东的CK还是挺好抓的 ，而且还有自动化的软件 。(上面只是一个跟这个可能有点相关需求，大哥 您要是方便的话 可以看看能不能做个这种类似的 因为我搜了半天 好像这上面还没有人做这种脚本 )
https://gw.smart.jd.com:443/f/service/controlxxxxxxx
![Screenshot_2024-11-03-17-19-42-126_com.jdcloud.mt.smartrouter.jpg](https://github.com/user-attachments/assets/5eb7bd4c-7029-45e5-a3c7-d42d2a6e9e9b)


![Screenshot_2024-11-03-17-20-01-381_com.minhui.networkcapture.jpg](https://github.com/user-attachments/assets/3e818326-2b7f-4a51-8ea9-ae5b6e26a066)

**Comment by jiangood** [comment]
> > 可以，正好最近有时间了
> 
> nice。其实我最近我发现有一个比较小众的需求(别的) ，不知道您这边有时间的话是否可以看一看能不能也做个类似的 青龙脚本或docker运行或者apk也可以。 京东有一个APP叫京东云无线宝 ，很多朋友都有用那种 监工的软件 ，需要抓包无限宝里面的tgt参数拿来登录获取信息。但是这个抓包很麻烦 ，所以我一直有个想法 ，如果有大哥可以研究一下京东的ck和京东云无线宝的tgt的关系。 (京东CK不知道是否可以直接登录京东无限宝 ，然后再通过某种技术手段直接抓取tgt，就不需要我们直接打开无限宝APP用抓包软件去抓了 )。因为京东的CK还是挺好抓的 ，而且还有自动化的软件 。(上面只是一个跟这个可能有点相关需求，大哥 您要是方便的话 可以看看能不能做个这种类似的 因为我搜了半天 好像这上面还没有人做这种脚本 ) https://gw.smart.jd.com:443/f/service/controlxxxxxxx ![Screenshot_2024-11-03-17-19-42-126_com.jdcloud.mt.smartrouter.jpg](https://private-user-images.githubusercontent.com/170397495/382559776-5eb7bd4c-7029-45e5-a3c7-d42d2a6e9e9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTgwMTEsIm5iZiI6MTczMDY5NzcxMSwicGF0aCI6Ii8xNzAzOTc0OTUvMzgyNTU5Nzc2LTVlYjdiZDRjLTcwMjktNDVlNS1hM2M3LWQ0MmQyYTZlOWU5Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNTIxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzc0ZDUzNGRjNjFhNjdiMjNkZGFiZTFkNTI2ODY1MjlhYmZhNjY0NGIwNmUwYWJlZjQ3NGM5YmFmOTYzY2RhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uQsM_iDMsaUfu7-kXAvov0fh0wx7hcjoUahlDrx1vys)
> 
> ![Screenshot_2024-11-03-17-20-01-381_com.minhui.networkcapture.jpg](https://private-user-images.githubusercontent.com/170397495/382559780-3e818326-2b7f-4a51-8ea9-ae5b6e26a066.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTgwMTEsIm5iZiI6MTczMDY5NzcxMSwicGF0aCI6Ii8xNzAzOTc0OTUvMzgyNTU5NzgwLTNlODE4MzI2LTJiN2YtNGE1MS04ZWE5LWFlNWI2ZTI2YTA2Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNTIxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2JmNjM3MDA5NDFiOTQyMGIzMWFmODFlYzFjOTNlNWI2NjY5YzU5MjliODZkN2FjYjUwODI3NzM5ZTg1NDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YLRqALEGsiPPc-zE5YBWEUFBFtvlwHZcmvnXszU-gB8)

没啥时间研究咯

**Comment by jiangood** [comment]
> rt。因为他有些脚本获取这个 但是并不一定就是这个名字 ，对于我们对代码不熟悉的也没办法去改它的脚本 。如果可以自定义上传的这个变量名就好了

已增加该功能
