### ISSUE TITLE
上传的ck格式不对，需要手动修改格式

### ISSUE THREAD

**Issue by bhsaxo** [moon-cn/qinglong-jd-app#18]

**Comment by l9970509** [comment]
ptpin 和 ptkey的顺序错了 一些脚本不识别cookie 希望作者修正

**Comment by jiangood** [comment]
是不是交换顺序

**Comment by l9970509** [comment]
> ptpin 和 ptkey的顺序错了 一些脚本不识别cookie 希望作者修正

看了一下源码，把
![image](https://github.com/user-attachments/assets/2aeab7c4-cc52-4225-ad0b-6e68eaa32403)
这个Java文件里的第24行
![image](https://github.com/user-attachments/assets/fd00f98d-ccbf-4a88-bea9-923f2172ad44)
cookie的ptpin和ptkey改成正确的顺序就可以了

**Comment by l9970509** [comment]
> 是不是交换顺序

对的 但是我fuh复刻项目 修改完顺序 打包出错了
![image](https://github.com/user-attachments/assets/0a36a6fd-8069-4c6e-955b-154efa78dd9c)
