### ISSUE TITLE
上传的ck缺少最后一个分号，格式不对

### ISSUE THREAD

**Issue by S091** [moon-cn/qinglong-jd-app#19]

**Comment by summer19940609** [comment]
我fork改了一下，https://github.com/summer19940609/qinglong-jd-apk/releases/download/v1.0.3/app-ci-release.apk，添加了分号

**Comment by drw2005** [comment]
> 我fork改了一下，[https://github.com/summer19940609/qinglong-jd-apk/releases/download/v1.0.3/app-ci-release.apk，添加了分号](https://github.com/summer19940609/qinglong-jd-apk/releases/download/v1.0.3/app-ci-release.apk%EF%BC%8C%E6%B7%BB%E5%8A%A0%E4%BA%86%E5%88%86%E5%8F%B7)

试试你的，谢谢分享！
