### ISSUE TITLE
Cookie同步失败

### ISSUE THREAD

**Issue by 188199176** [moon-cn/qinglong-jd-app#2]
报以下错误 
Expected URL scheme 'http' or 'https'
but no colon was found

**Comment by jiangood** [comment]
正在修复中...

**Comment by jiangood** [comment]
已修复。 
 由于使用github密码方式，自然想到使用linux 命令 sed 替换密码，没考虑到 url 中含有斜杠， 如http://xxx.com。
这个斜杠和sed命令中的斜杠冲突了。修改为#即可。
 主要还是因为对linux 的sed命令不熟悉
