### ISSUE TITLE
大佬 最新版1.0.7 cookie还是顺序错误

### ISSUE THREAD

**Issue by l9970509** [moon-cn/qinglong-jd-app#20]
![image](https://github.com/user-attachments/assets/dbdaab13-7e21-458c-97db-21f3dfcac848)
大佬 最新版1.0.7 cookie还是顺序错误

**Comment by jiangood** [comment]
手机改的，我再看看哈

**Comment by jiangood** [comment]
修改了一版

**Comment by l9970509** [comment]
> 修改了一版

1.0.8已测试 cookie值顺序正确 感谢
