### ISSUE TITLE
app青龙面板登陆选项为灰，无法点击

### ISSUE THREAD

**Issue by qingniaoheyu** [moon-cn/qinglong-jd-app#8]
请问下app需要啥权限吗

**Comment by jiangood** [comment]
应该可以点的，本身颜色就是灰色

**Comment by qingniaoheyu** [comment]
可以的，我的手机需要在输入密码后回车后，登陆才可选，给有相同需求的人做个备注。谢谢大佬

**Comment by xfchu1988** [comment]
@qingniaoheyu 请问在手机的哪个界面输入密码？

**Comment by jiangood** [comment]
![Screenshot_2024-08-16-12-30-56-74_b423e59be4f570d9793800e37c41be68.jpg](https://github.com/user-attachments/assets/12566385-5a57-47d2-a549-f0e42cb01acf)

**Comment by xfchu1988** [comment]
@mxvc 感谢大佬答复，点击这个登录青龙的界面后，显示要输入青龙url，我的青龙安装在本地局域网内，如何填写url？是否还要填写端口？我手机也登录相同的局域网，都试过了，“登录”依然是灰色不能点击，如何处理？
![微信图片_20240816133142](https://github.com/user-attachments/assets/ee9c50a9-fb4d-4c30-8904-3fc52c18bf27)

**Comment by jiangood** [comment]
从浏览器上复制，一般书http://开头的，手机记得连WiFi

**Comment by xfchu1988** [comment]
![1723786816435](https://github.com/user-attachments/assets/3517d944-84a7-41f8-9a3b-fad6d0f1b6b5)

**Comment by xfchu1988** [comment]
这是我青龙登录日志显示的IP地址，如何填写呢？谢谢答复！

**Comment by xfchu1988** [comment]
![227f0e24938da28863aae89b0e8e630](https://github.com/user-attachments/assets/381c30bd-4b0a-4bd4-b947-c5319c9318bf)
填写端口也不行，ip改成本地ip地址也不行，请指教，多谢了！

**Comment by qingniaoheyu** [comment]
> 
输入法回车

**Comment by xfchu1988** [comment]
@qingniaoheyu 多谢大佬指点了，已登录上了，青龙url填写为http://服务器地址+端口，然后最后敲一个回车，才能登录，多谢！

**Comment by xfchu1988** [comment]
@mxvc 建议增加一个清除缓存（方便快速退出）的功能，这样可以快速的登录上传多个账户！另外能否把最后的回车在填完三个参数后自动执行呢，谢谢！

**Comment by jiangood** [comment]
@xfchu1988 好的，加入待办

**Comment by jiangood** [comment]
已增加

> @mxvc 建议增加一个清除缓存（方便快速退出）的功能，这样可以快速的登录上传多个账户！另外能否把最后的回车在填完三个参数后自动执行呢，谢谢！

已添加该功能
